// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://typvhtyniskaiyukegzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5cHZodHluaXNrYWl5dWtlZ3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczOTgyNDgsImV4cCI6MjA2Mjk3NDI0OH0.eBk5rhefiN9suq9gv7oqqNkkqb9Ai6Z8F3S8Hqs9-G8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);